/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import dto.ReporteDTO;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.persistence.EntityManager;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import negocio.FachadaReporte;
import negocio.IFachadaReporte;
import negocio.IReporteNegocio;
import negocio.NegocioException;
import negocio.ReporteNegocio;

/**
 *
 * @author Beto_
 */
public class frmNavegacion extends javax.swing.JFrame {
    private static EntityManager entityManager;
    private IFachadaReporte fachadaReporte;
    private DefaultComboBoxModel<String> comboBoxModel;
    private String calleAnterior = null;
    private SwingWorker<Void, Void> worker = null;
    private boolean isWorkerRunning = false;
    /**
     * Creates new form frmNavegacion
     * @param entityManager
     */
    public frmNavegacion(EntityManager entityManager) {
        initComponents();
        this.entityManager = entityManager;
        this.fachadaReporte = new FachadaReporte(entityManager);

        comboBoxModel = new DefaultComboBoxModel<>();
        cbxFiltroCalle.setModel(comboBoxModel);

        llenarPaneles(null);

        configurarListenerComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnl1 = new javax.swing.JPanel();
        pnl2 = new javax.swing.JPanel();
        scrPanel = new javax.swing.JScrollPane();
        pnlPrincipal = new javax.swing.JPanel();
        brnCerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOpcionReporte = new javax.swing.JButton();
        cbxFiltroCalle = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 500));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(800, 420));

        pnl1.setBackground(new java.awt.Color(204, 204, 255));
        pnl1.setPreferredSize(new java.awt.Dimension(800, 450));

        pnl2.setBackground(new java.awt.Color(102, 153, 255));
        pnl2.setPreferredSize(new java.awt.Dimension(800, 420));

        scrPanel.setPreferredSize(new java.awt.Dimension(750, 350));

        pnlPrincipal.setPreferredSize(new java.awt.Dimension(750, 350));

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 767, Short.MAX_VALUE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        scrPanel.setViewportView(pnlPrincipal);

        brnCerrarSesion.setText("Cerrar sesión");
        brnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnCerrarSesionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Navegación");

        btnOpcionReporte.setText("Crear reporte");
        btnOpcionReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionReporteActionPerformed(evt);
            }
        });

        cbxFiltroCalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(brnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cbxFiltroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                        .addComponent(btnOpcionReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(pnl2Layout.createSequentialGroup()
                        .addComponent(scrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(brnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxFiltroCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOpcionReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(scrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnl1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcionReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionReporteActionPerformed
        // TODO add your handling code here:
        frmReporte frmReporte = new frmReporte(entityManager);
        frmReporte.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnOpcionReporteActionPerformed

    private void brnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnCerrarSesionActionPerformed
        // TODO add your handling code here:
        frmInicioSesion frmInicioSesion = new frmInicioSesion(entityManager);
        frmInicioSesion.setVisible(true);
        dispose();
    }//GEN-LAST:event_brnCerrarSesionActionPerformed

    private void configurarListenerComboBox() {
        cbxFiltroCalle.addActionListener(e -> {
        cbxFiltroCalle.setEnabled(false);

        String seleccion = (String) cbxFiltroCalle.getSelectedItem();
        llenarPaneles("Todas las calles".equals(seleccion) ? null : seleccion);
        });
    }

    private void llenarPaneles(String filtroCalle) {
        if (isWorkerRunning) return;
        isWorkerRunning = true;

        SwingWorker<Void, Void> worker = new SwingWorker<>() {
            List<ReporteDTO> reportesDTO;
            List<String> callesDisponibles;

            @Override
            protected Void doInBackground() throws Exception {
                //Cargamos los datos en segundo plano
                double[] coordenadas = {27.4826, -109.9516, 27.5126, -109.9216};
                callesDisponibles = new ArrayList<>(Arrays.asList(fachadaReporte.obtenerCalles(coordenadas)));

                reportesDTO = (filtroCalle == null || filtroCalle.isEmpty())
                        ? fachadaReporte.obtenerReportes()
                        : fachadaReporte.obtenerReportesPorCalle(filtroCalle);
                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(frmNavegacion.this, "Error al cargar los datos.");
                    return;
                }

                SwingUtilities.invokeLater(() -> {
                    actualizarComboBox(callesDisponibles);
                    actualizarPaneles(reportesDTO);
                    cbxFiltroCalle.setEnabled(true);
                    isWorkerRunning = false;
                });
            }
        };
        worker.execute();
    }

    private void actualizarComboBox(List<String> callesDisponibles) {
        comboBoxModel.removeAllElements();
        comboBoxModel.addElement("Todas las calles");
        for (String calle : callesDisponibles) {
            comboBoxModel.addElement(calle);
        }
    }

    private void actualizarPaneles(List<ReporteDTO> reportesDTO) {
        pnlPrincipal.removeAll();
        pnlPrincipal.setLayout(new BoxLayout(pnlPrincipal, BoxLayout.Y_AXIS));

        for (ReporteDTO reporteDTO : reportesDTO) {
            JPanel panelReporte = crearPanelReporte(reporteDTO);
            pnlPrincipal.add(panelReporte);
        }

        // Ajustar el tamaño del panl a partir de los reportes extraidos de la bd
        pnlPrincipal.setPreferredSize(new Dimension(scrPanel.getWidth(), reportesDTO.size() * 200));
        pnlPrincipal.revalidate();
        pnlPrincipal.repaint();
    }

    private JPanel crearPanelReporte(ReporteDTO reporteDTO) {
        AtomicBoolean like = new AtomicBoolean(false);
        JPanel panelReporte = new JPanel();
        panelReporte.setBorder(BorderFactory.createTitledBorder(reporteDTO.getTitulo()));
        panelReporte.setLayout(new GridLayout(4, 1));

        JLabel lblFecha = new JLabel("Fecha: " + reporteDTO.getFecha());
        JLabel lblCalle = new JLabel("Calle: " + reporteDTO.getCalle());
        JLabel lblDescripcion = new JLabel("<html>" + reporteDTO.getDescripcion() + "</html>");
        JLabel lblLikes = new JLabel("Likes: " + reporteDTO.getLikes());

        JButton btnLike = new JButton("Like");
        btnLike.addActionListener(e -> {
            lblLikes.setText("Likes: " + incrementarLikes(reporteDTO, like.get()));
            lblLikes.revalidate();
            lblLikes.repaint();
            like.set(!like.get());
        });

        panelReporte.add(lblFecha);
        panelReporte.add(lblCalle);
        panelReporte.add(lblDescripcion);

        JPanel likePanel = new JPanel(new FlowLayout(FlowLayout.LEFT));
        likePanel.add(lblLikes);
        likePanel.add(btnLike);

        panelReporte.add(likePanel);
        return panelReporte;
    }
    
    public int incrementarLikes(ReporteDTO reporteDTO, boolean like){        
        try{
            return fachadaReporte.likearReporte(reporteDTO, like);
        }catch(NegocioException ne){
            JOptionPane.showMessageDialog(this, "Error");
        }
        return reporteDTO.getLikes();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNavegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNavegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNavegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNavegacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNavegacion(entityManager).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnCerrarSesion;
    private javax.swing.JButton btnOpcionReporte;
    private javax.swing.JComboBox<String> cbxFiltroCalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JScrollPane scrPanel;
    // End of variables declaration//GEN-END:variables

}
